# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_onglet.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.setEnabled(True)
        TabWidget.resize(1054, 731)
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.table_search = QtWidgets.QTableWidget(self.tab)
        self.table_search.setGeometry(QtCore.QRect(10, 340, 1021, 221))
        self.table_search.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table_search.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table_search.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_search.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_search.setAlternatingRowColors(True)
        self.table_search.setRowCount(0)
        self.table_search.setColumnCount(0)
        self.table_search.setObjectName("table_search")
        self.dockWidget_4 = QtWidgets.QDockWidget(self.tab)
        self.dockWidget_4.setGeometry(QtCore.QRect(10, 10, 1031, 271))
        self.dockWidget_4.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        self.dockWidget_4.setObjectName("dockWidget_4")
        self.dockWidgetContents_6 = QtWidgets.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButton_50 = QtWidgets.QRadioButton(self.dockWidgetContents_6)
        self.radioButton_50.setObjectName("radioButton_50")
        self.gridLayout_2.addWidget(self.radioButton_50, 1, 1, 1, 1)
        self.radioButton_51 = QtWidgets.QRadioButton(self.dockWidgetContents_6)
        self.radioButton_51.setObjectName("radioButton_51")
        self.gridLayout_2.addWidget(self.radioButton_51, 3, 2, 1, 1)
        self.radioButton_64 = QtWidgets.QRadioButton(self.dockWidgetContents_6)
        self.radioButton_64.setObjectName("radioButton_64")
        self.gridLayout_2.addWidget(self.radioButton_64, 5, 2, 1, 1)
        self.radioButton_52 = QtWidgets.QRadioButton(self.dockWidgetContents_6)
        self.radioButton_52.setObjectName("radioButton_52")
        self.gridLayout_2.addWidget(self.radioButton_52, 2, 1, 1, 1)
        self.radioButton_59 = QtWidgets.QRadioButton(self.dockWidgetContents_6)
        self.radioButton_59.setObjectName("radioButton_59")
        self.gridLayout_2.addWidget(self.radioButton_59, 4, 1, 1, 1)
        self.radioButton_58 = QtWidgets.QRadioButton(self.dockWidgetContents_6)
        self.radioButton_58.setObjectName("radioButton_58")
        self.gridLayout_2.addWidget(self.radioButton_58, 3, 1, 1, 1)
        self.radioButton_49 = QtWidgets.QRadioButton(self.dockWidgetContents_6)
        self.radioButton_49.setObjectName("radioButton_49")
        self.gridLayout_2.addWidget(self.radioButton_49, 3, 0, 1, 1)
        self.radioButton_54 = QtWidgets.QRadioButton(self.dockWidgetContents_6)
        self.radioButton_54.setObjectName("radioButton_54")
        self.gridLayout_2.addWidget(self.radioButton_54, 2, 2, 1, 1)
        self.radioButton_63 = QtWidgets.QRadioButton(self.dockWidgetContents_6)
        self.radioButton_63.setObjectName("radioButton_63")
        self.gridLayout_2.addWidget(self.radioButton_63, 4, 2, 1, 1)
        self.radioButton_61 = QtWidgets.QRadioButton(self.dockWidgetContents_6)
        self.radioButton_61.setObjectName("radioButton_61")
        self.gridLayout_2.addWidget(self.radioButton_61, 0, 1, 1, 1)
        self.radioButton_62 = QtWidgets.QRadioButton(self.dockWidgetContents_6)
        self.radioButton_62.setObjectName("radioButton_62")
        self.gridLayout_2.addWidget(self.radioButton_62, 2, 0, 1, 1)
        self.radioButton_56 = QtWidgets.QRadioButton(self.dockWidgetContents_6)
        self.radioButton_56.setObjectName("radioButton_56")
        self.gridLayout_2.addWidget(self.radioButton_56, 1, 0, 1, 1)
        self.radioButton_55 = QtWidgets.QRadioButton(self.dockWidgetContents_6)
        self.radioButton_55.setChecked(True)
        self.radioButton_55.setObjectName("radioButton_55")
        self.gridLayout_2.addWidget(self.radioButton_55, 0, 0, 1, 1)
        self.radioButton_53 = QtWidgets.QRadioButton(self.dockWidgetContents_6)
        self.radioButton_53.setObjectName("radioButton_53")
        self.gridLayout_2.addWidget(self.radioButton_53, 1, 2, 1, 1)
        self.radioButton_60 = QtWidgets.QRadioButton(self.dockWidgetContents_6)
        self.radioButton_60.setObjectName("radioButton_60")
        self.gridLayout_2.addWidget(self.radioButton_60, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.dockWidgetContents_6)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 3, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.dockWidgetContents_6)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 1, 3, 1, 1)
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.dockWidgetContents_6)
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.gridLayout_2.addWidget(self.commandLinkButton_2, 2, 3, 1, 1)
        self.radioButton_57 = QtWidgets.QRadioButton(self.dockWidgetContents_6)
        self.radioButton_57.setObjectName("radioButton_57")
        self.gridLayout_2.addWidget(self.radioButton_57, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.dockWidget_4.setWidget(self.dockWidgetContents_6)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(10, 590, 191, 16))
        self.label_11.setObjectName("label_11")
        self.table_search_2 = QtWidgets.QTableWidget(self.tab)
        self.table_search_2.setGeometry(QtCore.QRect(10, 620, 1021, 71))
        self.table_search_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_search_2.setRowCount(0)
        self.table_search_2.setColumnCount(0)
        self.table_search_2.setObjectName("table_search_2")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 320, 241, 16))
        self.label_8.setObjectName("label_8")
        self.spinBox_2 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_2.setGeometry(QtCore.QRect(170, 290, 51, 24))
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(230, 290, 61, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(20, 290, 151, 21))
        self.label_19.setObjectName("label_19")
        self.pushButton_26 = QtWidgets.QPushButton(self.tab)
        self.pushButton_26.setEnabled(False)
        self.pushButton_26.setGeometry(QtCore.QRect(300, 290, 80, 23))
        self.pushButton_26.setObjectName("pushButton_26")
        TabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 1021, 205))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.PredefinedQueries = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.PredefinedQueries.setContentsMargins(0, 0, 0, 0)
        self.PredefinedQueries.setObjectName("PredefinedQueries")
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.PredefinedQueries.addWidget(self.pushButton_4, 3, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.PredefinedQueries.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.PredefinedQueries.addWidget(self.pushButton_5, 2, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.PredefinedQueries.addWidget(self.pushButton_11, 5, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.PredefinedQueries.addWidget(self.pushButton_14, 2, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.PredefinedQueries.addWidget(self.pushButton_9, 3, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.PredefinedQueries.addWidget(self.pushButton_8, 2, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.PredefinedQueries.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_12.setObjectName("pushButton_12")
        self.PredefinedQueries.addWidget(self.pushButton_12, 1, 2, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_17.setObjectName("pushButton_17")
        self.PredefinedQueries.addWidget(self.pushButton_17, 5, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.PredefinedQueries.addWidget(self.pushButton_2, 5, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.PredefinedQueries.addWidget(self.pushButton_13, 1, 3, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.PredefinedQueries.addWidget(self.pushButton_3, 4, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.PredefinedQueries.addWidget(self.pushButton_10, 4, 1, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_15.setObjectName("pushButton_15")
        self.PredefinedQueries.addWidget(self.pushButton_15, 3, 2, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_16.setObjectName("pushButton_16")
        self.PredefinedQueries.addWidget(self.pushButton_16, 4, 2, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_18.setObjectName("pushButton_18")
        self.PredefinedQueries.addWidget(self.pushButton_18, 6, 2, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_19.setObjectName("pushButton_19")
        self.PredefinedQueries.addWidget(self.pushButton_19, 2, 3, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_20.setObjectName("pushButton_20")
        self.PredefinedQueries.addWidget(self.pushButton_20, 3, 3, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_21.setObjectName("pushButton_21")
        self.PredefinedQueries.addWidget(self.pushButton_21, 4, 3, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_22.setObjectName("pushButton_22")
        self.PredefinedQueries.addWidget(self.pushButton_22, 5, 3, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_23.setObjectName("pushButton_23")
        self.PredefinedQueries.addWidget(self.pushButton_23, 6, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.PredefinedQueries.addWidget(self.label_3, 0, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.PredefinedQueries.addWidget(self.label_4, 0, 2, 1, 2)
        self.table_predefined_queries = QtWidgets.QTableWidget(self.tab_3)
        self.table_predefined_queries.setGeometry(QtCore.QRect(10, 280, 1031, 401))
        self.table_predefined_queries.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table_predefined_queries.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table_predefined_queries.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_predefined_queries.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_predefined_queries.setAlternatingRowColors(True)
        self.table_predefined_queries.setObjectName("table_predefined_queries")
        self.table_predefined_queries.setColumnCount(0)
        self.table_predefined_queries.setRowCount(0)
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(10, 240, 151, 21))
        self.label_15.setObjectName("label_15")
        self.spinBox = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox.setGeometry(QtCore.QRect(170, 240, 51, 24))
        self.spinBox.setMinimum(1)
        self.spinBox.setObjectName("spinBox")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(230, 240, 61, 21))
        self.label_17.setObjectName("label_17")
        self.pushButton_25 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_25.setEnabled(False)
        self.pushButton_25.setGeometry(QtCore.QRect(300, 240, 80, 23))
        self.pushButton_25.setObjectName("pushButton_25")
        TabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(330, 90, 701, 281))
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QtCore.QRect(330, 390, 701, 21))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(650, 40, 211, 31))
        self.label.setObjectName("label")
        self.dockWidget_6 = QtWidgets.QDockWidget(self.tab_2)
        self.dockWidget_6.setGeometry(QtCore.QRect(10, 70, 311, 601))
        self.dockWidget_6.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        self.dockWidget_6.setObjectName("dockWidget_6")
        self.dockWidgetContents_8 = QtWidgets.QWidget()
        self.dockWidgetContents_8.setObjectName("dockWidgetContents_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dockWidgetContents_8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButton_33 = QtWidgets.QRadioButton(self.dockWidgetContents_8)
        self.radioButton_33.setChecked(True)
        self.radioButton_33.setObjectName("radioButton_33")
        self.verticalLayout_4.addWidget(self.radioButton_33)
        self.radioButton_34 = QtWidgets.QRadioButton(self.dockWidgetContents_8)
        self.radioButton_34.setChecked(False)
        self.radioButton_34.setObjectName("radioButton_34")
        self.verticalLayout_4.addWidget(self.radioButton_34)
        self.radioButton_35 = QtWidgets.QRadioButton(self.dockWidgetContents_8)
        self.radioButton_35.setCheckable(True)
        self.radioButton_35.setChecked(False)
        self.radioButton_35.setAutoRepeat(False)
        self.radioButton_35.setObjectName("radioButton_35")
        self.verticalLayout_4.addWidget(self.radioButton_35)
        self.radioButton_36 = QtWidgets.QRadioButton(self.dockWidgetContents_8)
        self.radioButton_36.setChecked(False)
        self.radioButton_36.setObjectName("radioButton_36")
        self.verticalLayout_4.addWidget(self.radioButton_36)
        self.radioButton_37 = QtWidgets.QRadioButton(self.dockWidgetContents_8)
        self.radioButton_37.setObjectName("radioButton_37")
        self.verticalLayout_4.addWidget(self.radioButton_37)
        self.radioButton_38 = QtWidgets.QRadioButton(self.dockWidgetContents_8)
        self.radioButton_38.setObjectName("radioButton_38")
        self.verticalLayout_4.addWidget(self.radioButton_38)
        self.radioButton_39 = QtWidgets.QRadioButton(self.dockWidgetContents_8)
        self.radioButton_39.setObjectName("radioButton_39")
        self.verticalLayout_4.addWidget(self.radioButton_39)
        self.radioButton_40 = QtWidgets.QRadioButton(self.dockWidgetContents_8)
        self.radioButton_40.setObjectName("radioButton_40")
        self.verticalLayout_4.addWidget(self.radioButton_40)
        self.radioButton_41 = QtWidgets.QRadioButton(self.dockWidgetContents_8)
        self.radioButton_41.setObjectName("radioButton_41")
        self.verticalLayout_4.addWidget(self.radioButton_41)
        self.radioButton_42 = QtWidgets.QRadioButton(self.dockWidgetContents_8)
        self.radioButton_42.setObjectName("radioButton_42")
        self.verticalLayout_4.addWidget(self.radioButton_42)
        self.radioButton_43 = QtWidgets.QRadioButton(self.dockWidgetContents_8)
        self.radioButton_43.setObjectName("radioButton_43")
        self.verticalLayout_4.addWidget(self.radioButton_43)
        self.radioButton_44 = QtWidgets.QRadioButton(self.dockWidgetContents_8)
        self.radioButton_44.setObjectName("radioButton_44")
        self.verticalLayout_4.addWidget(self.radioButton_44)
        self.radioButton_45 = QtWidgets.QRadioButton(self.dockWidgetContents_8)
        self.radioButton_45.setObjectName("radioButton_45")
        self.verticalLayout_4.addWidget(self.radioButton_45)
        self.radioButton_46 = QtWidgets.QRadioButton(self.dockWidgetContents_8)
        self.radioButton_46.setObjectName("radioButton_46")
        self.verticalLayout_4.addWidget(self.radioButton_46)
        self.radioButton_47 = QtWidgets.QRadioButton(self.dockWidgetContents_8)
        self.radioButton_47.setObjectName("radioButton_47")
        self.verticalLayout_4.addWidget(self.radioButton_47)
        self.radioButton_48 = QtWidgets.QRadioButton(self.dockWidgetContents_8)
        self.radioButton_48.setObjectName("radioButton_48")
        self.verticalLayout_4.addWidget(self.radioButton_48)
        self.btn_submit_insert_delete_3 = QtWidgets.QPushButton(self.dockWidgetContents_8)
        self.btn_submit_insert_delete_3.setObjectName("btn_submit_insert_delete_3")
        self.verticalLayout_4.addWidget(self.btn_submit_insert_delete_3)
        self.dockWidget_6.setWidget(self.dockWidgetContents_8)
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(60, 40, 161, 31))
        self.label_16.setObjectName("label_16")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(590, 480, 211, 31))
        self.label_9.setObjectName("label_9")
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setGeometry(QtCore.QRect(330, 520, 701, 23))
        self.comboBox.setObjectName("comboBox")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(650, 450, 59, 15))
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(660, 550, 59, 16))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(330, 580, 701, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_24.setEnabled(False)
        self.pushButton_24.setGeometry(QtCore.QRect(330, 630, 701, 21))
        self.pushButton_24.setObjectName("pushButton_24")
        TabWidget.addTab(self.tab_2, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "Database G06 Interface"))
        self.table_search.setSortingEnabled(True)
        self.radioButton_50.setText(_translate("TabWidget", "BedType"))
        self.radioButton_51.setText(_translate("TabWidget", "Calendars"))
        self.radioButton_64.setText(_translate("TabWidget", "ListingsHasAmenities"))
        self.radioButton_52.setText(_translate("TabWidget", "CancellationPolicy"))
        self.radioButton_59.setText(_translate("TabWidget", "ResponseTime"))
        self.radioButton_58.setText(_translate("TabWidget", "PropertyType"))
        self.radioButton_49.setText(_translate("TabWidget", "Amenities"))
        self.radioButton_54.setText(_translate("TabWidget", "Country"))
        self.radioButton_63.setText(_translate("TabWidget", "HostsHasVerifications"))
        self.radioButton_61.setText(_translate("TabWidget", "RoomType"))
        self.radioButton_62.setText(_translate("TabWidget", "Verifications"))
        self.radioButton_56.setText(_translate("TabWidget", "Listings"))
        self.radioButton_55.setText(_translate("TabWidget", "Hosts"))
        self.radioButton_53.setText(_translate("TabWidget", "City"))
        self.radioButton_60.setText(_translate("TabWidget", "Reviews"))
        self.label_6.setText(_translate("TabWidget", "Type to search..."))
        self.commandLinkButton_2.setText(_translate("TabWidget", "SEARCH"))
        self.radioButton_57.setText(_translate("TabWidget", "Neighborhoods"))
        self.label_11.setText(_translate("TabWidget", "FINAL RESULT :"))
        self.label_8.setText(_translate("TabWidget", "SELECT A RESULT IN THE TAB BELOW:"))
        self.label_18.setText(_translate("TabWidget", "/"))
        self.label_19.setText(_translate("TabWidget", "SELECT PAGE NUMBER : "))
        self.pushButton_26.setText(_translate("TabWidget", "Go"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "Search"))
        self.pushButton_4.setText(_translate("TabWidget", "Q3"))
        self.pushButton_7.setText(_translate("TabWidget", "Q6"))
        self.pushButton_5.setText(_translate("TabWidget", "Q2"))
        self.pushButton_11.setText(_translate("TabWidget", "Q10"))
        self.pushButton_14.setText(_translate("TabWidget", "Q12"))
        self.pushButton_9.setText(_translate("TabWidget", "Q8"))
        self.pushButton_8.setText(_translate("TabWidget", "Q7"))
        self.pushButton_6.setText(_translate("TabWidget", "Q1"))
        self.pushButton_12.setText(_translate("TabWidget", "Q11"))
        self.pushButton_17.setText(_translate("TabWidget", "Q15"))
        self.pushButton_2.setText(_translate("TabWidget", "Q5"))
        self.pushButton_13.setText(_translate("TabWidget", "Q17"))
        self.pushButton_3.setText(_translate("TabWidget", "Q4"))
        self.pushButton_10.setText(_translate("TabWidget", "Q9"))
        self.pushButton_15.setText(_translate("TabWidget", "Q13"))
        self.pushButton_16.setText(_translate("TabWidget", "Q14"))
        self.pushButton_18.setText(_translate("TabWidget", "Q16"))
        self.pushButton_19.setText(_translate("TabWidget", "Q18"))
        self.pushButton_20.setText(_translate("TabWidget", "Q19"))
        self.pushButton_21.setText(_translate("TabWidget", "Q20"))
        self.pushButton_22.setText(_translate("TabWidget", "Q21"))
        self.pushButton_23.setText(_translate("TabWidget", "Q22"))
        self.label_3.setText(_translate("TabWidget", "Simple queries"))
        self.label_4.setText(_translate("TabWidget", "Complex queries"))
        self.table_predefined_queries.setSortingEnabled(True)
        self.label_15.setText(_translate("TabWidget", "SELECT PAGE NUMBER : "))
        self.label_17.setText(_translate("TabWidget", "/"))
        self.pushButton_25.setText(_translate("TabWidget", "Go"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_3), _translate("TabWidget", "Queries"))
        self.pushButton.setText(_translate("TabWidget", "Insert"))
        self.label.setText(_translate("TabWidget", "INSERTION"))
        self.radioButton_33.setText(_translate("TabWidget", "Hosts"))
        self.radioButton_34.setText(_translate("TabWidget", "Listings"))
        self.radioButton_35.setText(_translate("TabWidget", "Verifications"))
        self.radioButton_36.setText(_translate("TabWidget", "Amenities"))
        self.radioButton_37.setText(_translate("TabWidget", "Reviews"))
        self.radioButton_38.setText(_translate("TabWidget", "RoomType"))
        self.radioButton_39.setText(_translate("TabWidget", "BedType"))
        self.radioButton_40.setText(_translate("TabWidget", "CancellationPolicy"))
        self.radioButton_41.setText(_translate("TabWidget", "PropertyType"))
        self.radioButton_42.setText(_translate("TabWidget", "ResponseTime"))
        self.radioButton_43.setText(_translate("TabWidget", "Neighborhoods"))
        self.radioButton_44.setText(_translate("TabWidget", "City"))
        self.radioButton_45.setText(_translate("TabWidget", "Country"))
        self.radioButton_46.setText(_translate("TabWidget", "Calendars"))
        self.radioButton_47.setText(_translate("TabWidget", "HostsHasVerifications"))
        self.radioButton_48.setText(_translate("TabWidget", "ListingsHasAmenities"))
        self.btn_submit_insert_delete_3.setText(_translate("TabWidget", "Select"))
        self.label_16.setText(_translate("TabWidget", "SELECT TABLE TO UPDATE"))
        self.label_9.setText(_translate("TabWidget", "In choosen table, delete rows with"))
        self.label_7.setText(_translate("TabWidget", "DELETION"))
        self.label_10.setText(_translate("TabWidget", "="))
        self.pushButton_24.setText(_translate("TabWidget", "Delete"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_2), _translate("TabWidget", "Insert/Delete"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabWidget = QtWidgets.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()
    sys.exit(app.exec_())
